#!/system/bin/sh
##################################################
## Voltage Control boot script by xan and nitr8 ##
##################################################
LOG_FILE=/data/volt_scheduler.log
rm -Rf $LOG_FILE

echo "Starting Insanity Volt Scheduler $( date +"%m-%d-%Y %H:%M:%S" )" | tee -a $LOG_FILE;
echo "Sleeping for 20 seconds to workaround oc not setting properly on stock derivatve roms..."
sleep 20
echo "Ok lets start working"
echo "Set MIN Scaling Frequency" | tee -a $LOG_FILE;
echo "100000" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq
echo ""
echo "---------------"

echo "Set MAX Scaling Frequency" | tee -a $LOG_FILE;
echo "1400000" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq
echo ""
echo "---------------"

echo "Set Scheduler for stl, bml and mmc" | tee -a $LOG_FILE;

for i in `ls /sys/block/stl*` /sys/block/bml* /sys/block/mmcblk* /sys/block/mtdblock* ; do
        echo "cfq" > $i/queue/scheduler;
        echo "$i/queue/scheduler";
done;
        echo "---------------";
echo "Set governor" | tee -a $LOG_FILE;
echo "pegasusq" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
echo ""
echo "---------------"

#UV_BEGIN#

echo "Set UV" | tee -a $LOG_FILE;
echo "1450 1425 1375 1313 1200 1150 1125 1100 1050 975 925 900 900 875 875 875 850 850 " > /sys/devices/system/cpu/cpu0/cpufreq/UV_mV_table
echo ""
echo "---------------"

#UV_END#




echo "Insanity Volt Scheduler finished at $( date +"%m-%d-%Y %H:%M:%S" )" | tee -a $LOG_FILE;





